language: ruby
cache: bundler

rvm:
  - 2.0.0

script: 'bundle exec rake test'

notifications:
  email:
    recipients:
      - dysonsimmons@gmail.com
    on_failure: change
    on_success: never

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
